# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HAPT <- function(x, groups, maxlevel = 10L, nu_states = 4L, tau_states = 4L, nu_lims = as.numeric( c(0.0,4.0)), tau_lims = as.numeric( c(0.0,4.0)), beta_nu = 1, beta_tau = 1) {
    .Call('_HAPT_HAPT', PACKAGE = 'HAPT', x, groups, maxlevel, nu_states, tau_states, nu_lims, tau_lims, beta_nu, beta_tau)
}

